---
- name: Install npm
  apt:
    name:
      - npm
    update_cache: yes
    state: present

- name: Install npm packages globally
  npm:
    name:
      - typescript
      - tspath
      - pm2
    global: yes

- name: Install pm2-logrotate
  ansible.builtin.command:
    cmd: pm2 install pm2-logrotate