---
#- name: Install npm
#  apt:
#    name:
#      - npm
#    update_cache: yes
#    state: present
#
#- name: Install tspath globally
#  npm:
#    name: tspath
#    global: yes
#
#- name: Install pm2 globally
#  npm:
#    name: pm2
#    global: yes
#
#- name: Install typescript globally
#  npm:
#    name: typescript
#    global: yes

- name: Install pm2-logrotate
  ansible.builtin.command:
    cmd: pm2 set pm2-logrotate:max_size 112M && pm2 set pm2-logrotate:compress true
  become: yes
  become_user: "{{ deploy_user }}"