---
- name: "install nvim"
  ansible.builtin.apt:
    name: neovim
    state: present

- name: "install pip nvim"
  ansible.builtin.apt:
    name: python3-neovim
    state: present

- name: "install fzf"
  ansible.builtin.apt:
    name: fzf
    state: present

- name: "install Plug"
  shell: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

