---
- name: Install Postgres.
  apt:
    name:
      - postgresql
      - postgresql-contrib
      - libpq-dev
      - python3-psycopg2
    state: present

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes

- name: Create the user database specified in vars
  become: true
  become_user: postgres
  postgresql_db: name='{{ db_user }}' template='template0' state=present

- name: Create the app database specified in vars
  become: true
  become_user: postgres
  postgresql_db: name={{ app_name }} template='template0' state=present

- name: Ensure user has access to the new database
  become: true
  become_user: postgres
  postgresql_user: db={{ app_name }} name={{ db_user }} password={{ db_password }} priv=ALL state=present
