---
- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: Check if certbot private key exists for any domain
  stat:
    path: "/etc/letsencrypt/live/{{ item }}/privkey.pem"
  loop: "{{ domains }}"
  register: certbot_key_results

- name: Set a variable if any private key exists
  set_fact:
    certbot_key_exists: true
  when: item.stat.exists
  loop: "{{ certbot_key_results.results }}"
  loop_control:
    label: "{{ item.item }}"
  no_log: true

- name: Set ngix config without SSL
  template:
    src: app_nginx_ip.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
    mode: 0644
  when: certbot_key_exists is not defined
  notify: restart nginx

- name: Set ngix config with SSL
  template:
    src: app_nginx_ssl.j2
    dest: /etc/nginx/sites-available/{{ app_name }}
    mode: 0644
  when: certbot_key_exists
  notify: restart nginx

- name: Link app site enabled config
  file:  # noqa 208
    src: /etc/nginx/sites-available/{{ app_name }}
    dest: /etc/nginx/sites-enabled/{{ app_name }}
    state: link
  notify: restart nginx

- name: Ensure default virtual host is removed.
  become: yes
  file:
    path: /etc/nginx/sites-available/default
    state: absent
  notify: restart nginx

- name: Ensure default virtual host is removed.
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Start and enable Nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
