---
- hosts: deploy
  vars:
    git_repo_url: https://github.com/DenDos/promptinator.git
    playbook_app_name: promptinator
    playbook_deploy_user: deploy
  become: true
  vars_files:
    - ./secret_vars.yaml
  tasks:
    - name: Check if repository exists
      ansible.builtin.stat:
        path: /home/{{ playbook_deploy_user }}/{{ playbook_app_name }}
      register: repo_dir

    - name: Clone Git repository if directory does not exist
      when: not repo_dir.stat.exists
      ansible.builtin.git:
        repo: "{{ git_repo_url }}"
        dest: /home/{{ playbook_deploy_user }}/{{ playbook_app_name }}
        clone: yes
        update: no
      become: yes
      become_user: "{{ playbook_deploy_user }}"

    - name: Create a shared directory
      when: not repo_dir.stat.exists
      ansible.builtin.file:
        path: /home/{{ playbook_deploy_user }}/shared
        state: directory
        mode: '0755'
      become: yes
      become_user: "{{ playbook_deploy_user }}"

    - name: Create empty .env file
      when: not repo_dir.stat.exists
      ansible.builtin.file:
        path: /home/{{ playbook_deploy_user }}/shared/.env
        state: touch
        mode: '0755'
      become: yes
      become_user: "{{ playbook_deploy_user }}"

    - name: Create .env symlink to shared folder
      when: not repo_dir.stat.exists
      ansible.builtin.file:
        src: /home/{{ playbook_deploy_user }}/shared/.env
        dest: /home/{{ playbook_deploy_user }}/{{ playbook_app_name }}/.env
        state: link

    - name: Checkout main branch and pull latest changes
      shell:
        cmd: |
          git config --global --add safe.directory /home/{{ playbook_deploy_user }}/{{ playbook_app_name }}
          git checkout main && git pull
        chdir: /home/{{ playbook_deploy_user }}/{{ playbook_app_name }}
      become: yes
      become_user: "{{ playbook_deploy_user }}"

    - name: Restart the app
      shell:
        cmd: npm install && npm run build && npm run start:prod
        chdir: /home/{{ playbook_deploy_user }}/{{ playbook_app_name }}
      become: yes
      become_user: "{{ playbook_deploy_user }}"